version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
        environment:
          DATABASE_URL: "postgres://ubuntu:@localhost/circle_test"
          DJANGO_SETTINGS_MODULE: "eggtimer.settings"
          DJANGO_DEBUG: 0
          DJANGO_ENABLE_SSL: 0
    steps:
      - checkout
      # https://discuss.circleci.com/t/circleci-python-docker-images-disallow-pip-install-due-to-directory-ownership/12504
      - run: pip install --user -r requirements/development.txt
